trying to authenticate, running into some error
com.fasterxml.jackson.databind.JsonMappingException: No suitable
constructor found for type [simple type, class com.iote.web.core.User]:
can not instantiate from JSON object (missing default constructor or
creator, or perhaps need to add/enable type information?)